spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OuYangLiang/eureka-config
          username: xxx
          password: 'xxx'

server:
  port: 9999